CREATE TABLE IF NOT EXISTS `xdb_countries` (
`id` integer not null auto_increment primary key,
`name` char(50) not null comment 'Наименование страны'
)
ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO `xdb_countries` (name) VALUES ("Австралия");
INSERT INTO `xdb_countries` (name) VALUES ("Австрия");
INSERT INTO `xdb_countries` (name) VALUES ("Азербайджан");
INSERT INTO `xdb_countries` (name) VALUES ("Албания");
INSERT INTO `xdb_countries` (name) VALUES ("Алжир");
INSERT INTO `xdb_countries` (name) VALUES ("Ангола");
INSERT INTO `xdb_countries` (name) VALUES ("Андорра");
INSERT INTO `xdb_countries` (name) VALUES ("Антигуа");
INSERT INTO `xdb_countries` (name) VALUES ("Аргентина");
INSERT INTO `xdb_countries` (name) VALUES ("Армения");
INSERT INTO `xdb_countries` (name) VALUES ("Афганистан");
INSERT INTO `xdb_countries` (name) VALUES ("Багамские острова");
INSERT INTO `xdb_countries` (name) VALUES ("Бангладеш");
INSERT INTO `xdb_countries` (name) VALUES ("Барбадос");
INSERT INTO `xdb_countries` (name) VALUES ("Бахрейн");
INSERT INTO `xdb_countries` (name) VALUES ("Беларусь");
INSERT INTO `xdb_countries` (name) VALUES ("Белиз");
INSERT INTO `xdb_countries` (name) VALUES ("Бельгия");
INSERT INTO `xdb_countries` (name) VALUES ("Бенин");
INSERT INTO `xdb_countries` (name) VALUES ("Болгария");
INSERT INTO `xdb_countries` (name) VALUES ("Боливия");
INSERT INTO `xdb_countries` (name) VALUES ("Босния и Герцеговина");
INSERT INTO `xdb_countries` (name) VALUES ("Ботсвана");
INSERT INTO `xdb_countries` (name) VALUES ("Бразилия");
INSERT INTO `xdb_countries` (name) VALUES ("Бруней");
INSERT INTO `xdb_countries` (name) VALUES ("Буркина-Фасо");
INSERT INTO `xdb_countries` (name) VALUES ("Бурунди");
INSERT INTO `xdb_countries` (name) VALUES ("Бутан");
INSERT INTO `xdb_countries` (name) VALUES ("Вануату");
INSERT INTO `xdb_countries` (name) VALUES ("Ватикан");
INSERT INTO `xdb_countries` (name) VALUES ("Великобритания");
INSERT INTO `xdb_countries` (name) VALUES ("Венгрия");
INSERT INTO `xdb_countries` (name) VALUES ("Венесуела");
INSERT INTO `xdb_countries` (name) VALUES ("Вьетнам");
INSERT INTO `xdb_countries` (name) VALUES ("Габон");
INSERT INTO `xdb_countries` (name) VALUES ("Гаити");
INSERT INTO `xdb_countries` (name) VALUES ("Гайана");
INSERT INTO `xdb_countries` (name) VALUES ("Гамбия");
INSERT INTO `xdb_countries` (name) VALUES ("Гана");
INSERT INTO `xdb_countries` (name) VALUES ("Гватемала");
INSERT INTO `xdb_countries` (name) VALUES ("Гвинея");
INSERT INTO `xdb_countries` (name) VALUES ("Гвинея-Бисау");
INSERT INTO `xdb_countries` (name) VALUES ("Германия");
INSERT INTO `xdb_countries` (name) VALUES ("Гондурас");
INSERT INTO `xdb_countries` (name) VALUES ("Гренада");
INSERT INTO `xdb_countries` (name) VALUES ("Греция");
INSERT INTO `xdb_countries` (name) VALUES ("Грузия");
INSERT INTO `xdb_countries` (name) VALUES ("Дания");
INSERT INTO `xdb_countries` (name) VALUES ("Джибути");
INSERT INTO `xdb_countries` (name) VALUES ("Доминика");
INSERT INTO `xdb_countries` (name) VALUES ("Доминиканская республика");
INSERT INTO `xdb_countries` (name) VALUES ("Египет");
INSERT INTO `xdb_countries` (name) VALUES ("Замбия");
INSERT INTO `xdb_countries` (name) VALUES ("Зимбабве");
INSERT INTO `xdb_countries` (name) VALUES ("Израиль");
INSERT INTO `xdb_countries` (name) VALUES ("Индия");
INSERT INTO `xdb_countries` (name) VALUES ("Индонезия");
INSERT INTO `xdb_countries` (name) VALUES ("Иордания");
INSERT INTO `xdb_countries` (name) VALUES ("Ирак");
INSERT INTO `xdb_countries` (name) VALUES ("Иран");
INSERT INTO `xdb_countries` (name) VALUES ("Ирландия");
INSERT INTO `xdb_countries` (name) VALUES ("Исландия");
INSERT INTO `xdb_countries` (name) VALUES ("Испания");
INSERT INTO `xdb_countries` (name) VALUES ("Италия");
INSERT INTO `xdb_countries` (name) VALUES ("Йемен");
INSERT INTO `xdb_countries` (name) VALUES ("Кабо-Верде");
INSERT INTO `xdb_countries` (name) VALUES ("Казахстан");
INSERT INTO `xdb_countries` (name) VALUES ("Камбоджа");
INSERT INTO `xdb_countries` (name) VALUES ("Камерун");
INSERT INTO `xdb_countries` (name) VALUES ("Канада");
INSERT INTO `xdb_countries` (name) VALUES ("Катар");
INSERT INTO `xdb_countries` (name) VALUES ("Кения");
INSERT INTO `xdb_countries` (name) VALUES ("Кипр");
INSERT INTO `xdb_countries` (name) VALUES ("Киргизия");
INSERT INTO `xdb_countries` (name) VALUES ("Кирибати");
INSERT INTO `xdb_countries` (name) VALUES ("Китай");
INSERT INTO `xdb_countries` (name) VALUES ("Колумбия");
INSERT INTO `xdb_countries` (name) VALUES ("Коморские острова");
INSERT INTO `xdb_countries` (name) VALUES ("Конго");
INSERT INTO `xdb_countries` (name) VALUES ("Конго (демократическая республика)");
INSERT INTO `xdb_countries` (name) VALUES ("Коста-Рика");
INSERT INTO `xdb_countries` (name) VALUES ("Куба");
INSERT INTO `xdb_countries` (name) VALUES ("Кувейт");
INSERT INTO `xdb_countries` (name) VALUES ("Лаос");
INSERT INTO `xdb_countries` (name) VALUES ("Латвия");
INSERT INTO `xdb_countries` (name) VALUES ("Лесото");
INSERT INTO `xdb_countries` (name) VALUES ("Либерия");
INSERT INTO `xdb_countries` (name) VALUES ("Ливан");
INSERT INTO `xdb_countries` (name) VALUES ("Ливия");
INSERT INTO `xdb_countries` (name) VALUES ("Литва");
INSERT INTO `xdb_countries` (name) VALUES ("Лихтенштейн");
INSERT INTO `xdb_countries` (name) VALUES ("Люксембург");
INSERT INTO `xdb_countries` (name) VALUES ("Маврикий");
INSERT INTO `xdb_countries` (name) VALUES ("Мавритания");
INSERT INTO `xdb_countries` (name) VALUES ("Мадагаскар");
INSERT INTO `xdb_countries` (name) VALUES ("Македония");
INSERT INTO `xdb_countries` (name) VALUES ("Малави");
INSERT INTO `xdb_countries` (name) VALUES ("Малайзия");
INSERT INTO `xdb_countries` (name) VALUES ("Мали");
INSERT INTO `xdb_countries` (name) VALUES ("Мальдивы");
INSERT INTO `xdb_countries` (name) VALUES ("Мальта");
INSERT INTO `xdb_countries` (name) VALUES ("Марокко");
INSERT INTO `xdb_countries` (name) VALUES ("Маршаловы острова");
INSERT INTO `xdb_countries` (name) VALUES ("Мексика");
INSERT INTO `xdb_countries` (name) VALUES ("Микронезия");
INSERT INTO `xdb_countries` (name) VALUES ("Мозамбик");
INSERT INTO `xdb_countries` (name) VALUES ("Молдавия");
INSERT INTO `xdb_countries` (name) VALUES ("Монако");
INSERT INTO `xdb_countries` (name) VALUES ("Монголия");
INSERT INTO `xdb_countries` (name) VALUES ("Мьянма");
INSERT INTO `xdb_countries` (name) VALUES ("Намибия");
INSERT INTO `xdb_countries` (name) VALUES ("Науру");
INSERT INTO `xdb_countries` (name) VALUES ("Непал");
INSERT INTO `xdb_countries` (name) VALUES ("Нигер");
INSERT INTO `xdb_countries` (name) VALUES ("Нигерия");
INSERT INTO `xdb_countries` (name) VALUES ("Нидерланды");
INSERT INTO `xdb_countries` (name) VALUES ("Никарагуа");
INSERT INTO `xdb_countries` (name) VALUES ("Новая Зеландия");
INSERT INTO `xdb_countries` (name) VALUES ("Норвегия");
INSERT INTO `xdb_countries` (name) VALUES ("Объединенные Арабские Эмираты");
INSERT INTO `xdb_countries` (name) VALUES ("Оман");
INSERT INTO `xdb_countries` (name) VALUES ("Пакистан");
INSERT INTO `xdb_countries` (name) VALUES ("Палау");
INSERT INTO `xdb_countries` (name) VALUES ("Панама");
INSERT INTO `xdb_countries` (name) VALUES ("Папуа - Новая Гвинея");
INSERT INTO `xdb_countries` (name) VALUES ("Парагвай");
INSERT INTO `xdb_countries` (name) VALUES ("Перу");
INSERT INTO `xdb_countries` (name) VALUES ("Польша");
INSERT INTO `xdb_countries` (name) VALUES ("Португалия");
INSERT INTO `xdb_countries` (name) VALUES ("Россия");
INSERT INTO `xdb_countries` (name) VALUES ("Руанда");
INSERT INTO `xdb_countries` (name) VALUES ("Румыния");
INSERT INTO `xdb_countries` (name) VALUES ("Сальвадор");
INSERT INTO `xdb_countries` (name) VALUES ("Самоа");
INSERT INTO `xdb_countries` (name) VALUES ("Сан -Томе и Принсипи");
INSERT INTO `xdb_countries` (name) VALUES ("Сан-Марино");
INSERT INTO `xdb_countries` (name) VALUES ("Саудовская Аравия");
INSERT INTO `xdb_countries` (name) VALUES ("Свазиленд");
INSERT INTO `xdb_countries` (name) VALUES ("Северная Корея");
INSERT INTO `xdb_countries` (name) VALUES ("Сейшельские острова");
INSERT INTO `xdb_countries` (name) VALUES ("Сенегал");
INSERT INTO `xdb_countries` (name) VALUES ("Сент-Винсент");
INSERT INTO `xdb_countries` (name) VALUES ("Сингапур");
INSERT INTO `xdb_countries` (name) VALUES ("Сирия");
INSERT INTO `xdb_countries` (name) VALUES ("Словакия");
INSERT INTO `xdb_countries` (name) VALUES ("Словения");
INSERT INTO `xdb_countries` (name) VALUES ("Соломоновы острова");
INSERT INTO `xdb_countries` (name) VALUES ("Сомали");
INSERT INTO `xdb_countries` (name) VALUES ("Судан");
INSERT INTO `xdb_countries` (name) VALUES ("Суринам");
INSERT INTO `xdb_countries` (name) VALUES ("США");
INSERT INTO `xdb_countries` (name) VALUES ("Сьерра-Леоне");
INSERT INTO `xdb_countries` (name) VALUES ("Тайвань");
INSERT INTO `xdb_countries` (name) VALUES ("Тайланд");
INSERT INTO `xdb_countries` (name) VALUES ("Танзания");
INSERT INTO `xdb_countries` (name) VALUES ("Татжикистан");
INSERT INTO `xdb_countries` (name) VALUES ("Того");
INSERT INTO `xdb_countries` (name) VALUES ("Тонга");
INSERT INTO `xdb_countries` (name) VALUES ("Тринидад и Тобаго");
INSERT INTO `xdb_countries` (name) VALUES ("Тувалу");
INSERT INTO `xdb_countries` (name) VALUES ("Тунис");
INSERT INTO `xdb_countries` (name) VALUES ("Туркменистан");
INSERT INTO `xdb_countries` (name) VALUES ("Турция");
INSERT INTO `xdb_countries` (name) VALUES ("Уганда");
INSERT INTO `xdb_countries` (name) VALUES ("Узбекистан");
INSERT INTO `xdb_countries` (name) VALUES ("Украина");
INSERT INTO `xdb_countries` (name) VALUES ("Уругвай");
INSERT INTO `xdb_countries` (name) VALUES ("Фиджи");
INSERT INTO `xdb_countries` (name) VALUES ("Филиппины");
INSERT INTO `xdb_countries` (name) VALUES ("Финляндия");
INSERT INTO `xdb_countries` (name) VALUES ("Франция");
INSERT INTO `xdb_countries` (name) VALUES ("Хорватия");
INSERT INTO `xdb_countries` (name) VALUES ("Центрально-Африканская республика");
INSERT INTO `xdb_countries` (name) VALUES ("Чад");
INSERT INTO `xdb_countries` (name) VALUES ("Чехия");
INSERT INTO `xdb_countries` (name) VALUES ("Чили");
INSERT INTO `xdb_countries` (name) VALUES ("Швейцария");
INSERT INTO `xdb_countries` (name) VALUES ("Швеция");
INSERT INTO `xdb_countries` (name) VALUES ("Шри-Ланка");
INSERT INTO `xdb_countries` (name) VALUES ("Эквадор");
INSERT INTO `xdb_countries` (name) VALUES ("Экваториальная Гвинея");
INSERT INTO `xdb_countries` (name) VALUES ("Эритрея");
INSERT INTO `xdb_countries` (name) VALUES ("Эстония");
INSERT INTO `xdb_countries` (name) VALUES ("Эфиопия");
INSERT INTO `xdb_countries` (name) VALUES ("ЮАР");
INSERT INTO `xdb_countries` (name) VALUES ("Югославия");
INSERT INTO `xdb_countries` (name) VALUES ("Южная Корея");
INSERT INTO `xdb_countries` (name) VALUES ("Ямайка");
INSERT INTO `xdb_countries` (name) VALUES ("Япония");
